### ISSUE TITLE
upgrade for yml-based GitHub actions

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/ghpages#21]
maybe this can be a "host" aka "js" action?

Doesn't seem like this would really need a docker container.

**Comment by maxheld83** [comment]
asked support

**Comment by kayvanbree** [comment]
Right now it doesn't work for yml. It gives the following error:

```
error: src refspec @github.com/<user>/<repo>.git does not match any.
```

That was after using this config:

```
on: push
name: Build and publish
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build --prod
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR : dist/f10k
        GH_PAT: ${{ secrets.GH_PAT }}
```

I don't know if this is useful. I'm new to actions, but they changed it that this action can't run on the new format, right?
